### ISSUE TITLE
CirceJsonDeserializer fails when using Jackson's MappingIterator

### ISSUE THREAD

**Issue by lhotari** [circe/circe-jackson#18]
My usecase is to use `CirceJsonDeserializer` [in a library that uses Jackson's MappingIterator to deserialize an array of JSON objects](https://github.com/zalando-incubator/fahrschein/blob/a52ecb2/fahrschein/src/main/java/org/zalando/fahrschein/NakadiReader.java#L234) which are part of a larger JSON document. I'd like to get Circe `Json` instances returned from this library. There is a small bug in `circe-jackson` which prevents using `CirceJsonDeserializer` in this way. 

This is the exception I get: 
```
We weren't reading an object, something went wrong
java.lang.RuntimeException: We weren't reading an object, something went wrong
	at io.circe.jackson.CirceJsonDeserializer.deserialize(CirceJsonDeserializer.scala:74)
	at io.circe.jackson.CirceJsonDeserializer.deserialize(CirceJsonDeserializer.scala:40)
	at io.circe.jackson.CirceJsonDeserializer.deserialize(CirceJsonDeserializer.scala:35)
	at com.fasterxml.jackson.databind.MappingIterator.nextValue(MappingIterator.java:277)
	at com.fasterxml.jackson.databind.MappingIterator.next(MappingIterator.java:192)
```

I debugged the problem and found out the `CirceJsonDeserializer` [is consuming one extra token](https://github.com/circe/circe-jackson/blob/9236ce9/shared/src/main/scala/io/circe/jackson/CirceJsonDeserializer.scala#L92) and that's causing the failure.

I have a failing test case and fix for the issue, I'll send a PR.

**Comment by travisbrown** [comment]
Fixed in #19 and released in 0.7.1.
