### ISSUE TITLE
circe-jackson217 0.14.1 appears to be built with scoverage enabled

### ISSUE THREAD

**Issue by mjsmith707** [circe/circe-jackson#449]
I'm trying to use this library to convert some circe objects to jackson via:
`val node = io.circe.jackson.circeToJackson(circeJson)`
and I end up getting this error:

```
Caused by: java.io.FileNotFoundException: /home/runner/work/circe-jackson/circe-jackson/217/target/scala-2.13/scoverage-data/scoverage.measurements.99b494af-daa8-4ae0-b12d-c4a80fb093d0.1 (No such file or directory)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:113)
	at scoverage.Invoker$.$anonfun$invoked$1(Invoker.scala:65)
	at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:469)
	at scoverage.Invoker$.invoked(Invoker.scala:65)
	at io.circe.jackson.WithJacksonMapper.<init>(WithJacksonMapper.scala:27)
	at io.circe.jackson.package$.<init>(package.scala:39)
	at io.circe.jackson.package$.<clinit>(package.scala:39)
```

From some searching, this appears to be a known issue where scoverage is enabled when building a jar
https://github.com/scoverage/sbt-scoverage/issues/84
https://github.com/scoverage/sbt-scoverage/issues/306

The offending line looks to be https://github.com/circe/circe-jackson/blob/c2fc61380e3a81951241758c5b671ae4a249b5a8/build.sbt#L30
I'm using Scala 2.13.12 - presumably this works on Scala3 which I'm unable to use right now

**Comment by hamnis** [comment]
Wow! Seriously?
This will be fixed asap.
